language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
install:
  - npm install
  - npm install -g codecov
script:
  - npm run test:prod && npm run build
  - codecov --token=b61142de-9f3c-4c0f-8567-8deaa7d1f6f9
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
