language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
  - '6'
  - '4'
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
